version: '3'

services:
  # --- PROXY MÁGICO (jwilder) ---
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network

  # --- TUS SERVICIOS ---
  portainer:
    image: 'portainer/portainer-ce:2.21.5-alpine'
    container_name: portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.test
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-network

  prometheus:
    image: 'prom/prometheus:v3.1.0'
    container_name: prometheus
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=prometheus.test
      - VIRTUAL_PORT=9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus # <--- CORREGIDO: Ahora los datos se guardan
    networks:
      - monitoring-network
      - proxy-network

  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=grafana.test
      - VIRTUAL_PORT=3000
    volumes:
      - grafana_data:/var/lib/grafana # <--- CORREGIDO: Ahora tus Dashboards no se borran
    networks:
      - monitoring-network
      - proxy-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring-network

networks:
  proxy-network:
    external: true
  monitoring-network:
    external: true

# --- VOLÚMENES (AQUÍ ES DONDE SE GUARDA TODO) ---
volumes:
  portainer_data:
  prometheus_data: # <--- AÑADIDO
  grafana_data:    # <--- AÑADIDO
